config/routes.rb
SampleApp::Application.routes.draw do
  
  root 'static_pages#home'
  resources :users do
		member do
			get :following, :followers
		end
  end
  resources :microposts, 		only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :sessions, 			only: [:create, :destroy, :new]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  
  
  
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
		if signed_in?
			@micropost = current_user.microposts.build
			@feed_items = current_user.feed.paginate(page: params[:page])
		end	
  end
  
  def about
  end
  
  def contact
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
			<% provide(:title,'About Us') %>
			
			
		<p>		
			<h1>About Us</h1>
      This is the about page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      help with
      <a href="http://rubyonrails.org/"> Rails</a>. This
			sample application.
	  </p>
   

app/views/static_pages/contact.html.erb
<% provide(:title,'Contact') %>
    <h1>Contact</h1>
    <p>
      This is the contact page for 
      <a href="http://railstutorial.org/contact">contact</a>
      about sample application.
    </p>

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>

    <h1>Help</h1>
    <p>
      This is the help page for the
      <a href="http://railstutorial.org/help"> Rails Tutorial help page</a>
      To get help on this sample app, see the
	  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<div class="row">
	
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>	
		</section>
	
	</aside>
	
	<div class="span8">
		<h3>Micropost feed</h3>
		<%= render 'shared/feed' %>
	</div>
	
</div>   
<% else %>   
  <div class="center hero-unit">
	 <h1>Brickaway App</h1>
		<h2>
			This is the home page for the
			<a href="http://railstutorial.org/">Brickaway</a>
			 application.
		</h2>
			
		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	</div>
	<%= link_to image_tag("rails1.png", alt: "Rails", class: "img-circle"), 'http://rubyonrails.org/' %>

<% end %>