config/routes.rb
SampleApp::Application.routes.draw do
  
  root 'static_pages#home'
  resources :users do
		member do
			get :following, :followers
		end
  end
  resources :microposts, 		only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :sessions, 			only: [:create, :destroy, :new]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  
  
  
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts", id="feed">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
	
<% else %>
	<ol id="feed" class="microposts">
	</ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= wrap(feed_item.content) %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user) %>
		<%= link_to "delete", feed_item, method: :delete,
					data: { confirm: "you sure?" }, title: "sure ?" %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
	<section id="lettersLeft"></section>

	<script>
		function count(t,a) {
    var x = document.getElementById(a).value.length;
    var maxLetters = 140;
    var left = maxLetters -x ;
    if(left > 0)
    {
			document.getElementById(t).innerHTML = "leters left: "+ left;
		}
    else{
					document.getElementById(t).innerHTML = "letters left: "+ 0 + ".";
					document.getElementById(a).value = document.getElementById(a).value.substr(0, maxLetters - 1);
				}
    }
    
    
	//~ $("#micropost_content").keyup(function(){
															//~ var length = $(this).val().length;
															//~ var s = "<section> you have" +  (140-length) + "letters left.</section>";
															//~ $("div").append("<p>bbbbb</p>");
															//~ });

	
    
	</script>
	


<%= form_for(@micropost, remote: true) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost..." , oninput:'count("lettersLeft", "micropost_content")' %>
	</div>
	<%= f.submit "Post", class: "btn btn-primary btn-large" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 80), current_user %>
<h1><%= current_user.name %></h1>
<span class="">
	<%= link_to "view my profile", current_user %>
</span>
<span class="">
<%= pluralize(current_user.microposts.count, "micropost") %>
</span>